CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'HR_MANAGER', 'FINANCE_TEAM', 'EMPLOYEE');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'RETRYING');
CREATE TYPE "PaymentMethod" AS ENUM ('NEFT', 'IMPS', 'UPI');

